version: "3.7"
services:
  web:
    build: .
    entrypoint: nodemon --experimental-modules --es-module-specifier-resolution=node app.js
    ports:
      - 5000:5000
    volumes:
      - ./:/app/
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - 27027:27017